server:
  name: WebServer
  port: 8000
  threads: 5
db:
  name: PgConnPool
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456
  dbname: demo
  timeout: 10
  min_size: 5
  max_size: 10
